### ISSUE TITLE
document id parameter

### ISSUE THREAD

**Issue by Billos** [LiamMartens/sanity-plugin-autocomplete-input#1]
In order to query nested fields in a document, we need to be able to filter the groq query with the id of the current document
For instance like that : 

> groq: {
>           query: '*[_type == "dialog" && _id == **$docId**] { value: title }
> }

**Comment by Billos** [comment]
I would add as parameter the current complete path of the document / object

**Comment by LiahMartens** [comment]
It is now possible to provide a function to the `params` key to resolve dynamic parameters to the GROQ query. I decided not to add any parameters by default to not pollute the query scope so it is left up to the implementation.

See the new [README section](https://github.com/LiamMartens/sanity-plugin-autocomplete-input#advanced-groq-parameters) for more info
