### ISSUE TITLE
Array of options AND default groq query will execute

### ISSUE THREAD

**Issue by fabien** [LiamMartens/sanity-plugin-autocomplete-input#2]
It was my impression that setting hardcoded values as an array of `options` would only return those options. Instead, the default field (`title`) is used to query values from the dataset as well. Perhaps this is intentional, but it's not clear from the documentation that all options are currently considered.

Also, a small feature request: can you introduce an option to disable the 'add new' behavior?

**Comment by fabien** [comment]
In fact, it appears that the queried values always override the hardcoded ones.

**Comment by LiahMartens** [comment]
I have updated the logic to only use options when defined and thus ignore the GROQ query. This is more clear from a functional perpsective.
