### ISSUE TITLE
Disable "Create new option"

### ISSUE THREAD

**Issue by wundertaeter** [LiamMartens/sanity-plugin-autocomplete-input#3]
For our purpose we need a textfield that allows just specific options. Our creators should **not** be able to create new options. Instead they should only be able to select one of our provided. It would be a grate feature if you implement an option that allows us to disable the "Create new option" button in the autocomplete dropdown. 

Something like: 
{
  name: 'action',
  type: 'autocomplete',
  title: 'Action',
  options: {
    **allowNew: false,**
    groq: {
      query: '*[_type == $type]{"value": cta}',
      params: {
        type: 'config'
      },
      transform: (values) => values.flat()
    },
  }
},

I already tried to modify the "renderOption" method in the "AutoCompleteInput.tsx" file to return no children if the option is new but unfortunately that doesn't work. The autocomplete dropdown renders an empty button and I was still able to insert a new option. 

I would be excited to hear your opinion about this.

Greetings

**Comment by LiahMartens** [comment]
A new option was added called `disableNew` which can be set to `true` to disable the creation of new options. The naming is in line with Sanity's naming for the `reference` type.
