### ISSUE TITLE
upgrade to v3

### ISSUE THREAD

**Issue by johannesmutter** [LiamMartens/sanity-plugin-autocomplete-input#5]
Hi, 
I was wondering if there's a roadmap/ plan to upgrade this plugin for sanity v3?
https://www.sanity.io/docs/migrating-from-v2#c171df4dd957

And is this plugin build in a similar way as outline in these two guides?
https://www.sanity.io/schemas/asynchronous-list-options-component-05f63a29
https://www.sanity.io/ui/docs/component/autocomplete#example-with-custom-rendering

**Comment by LiahMartens** [comment]
@johannesmutter sorry for the late response :joy: - the plugin has now been updated to V3
